name: flutter_synthizer
version: 0.1.0
description: "Handle Synthizer objects from Flutter."
homepage: https://github.com/chrisnorman7/flutter_synthizer.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
