name: flutter_synthizer
description: "Handle Synthizer objects from Flutter."
version: 0.0.1
homepage: https://github.com/chrisnorman7/flutter_synthizer.git

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
